'use strict';
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let actFilter=0;
const main=document.querySelector('main');
const frames={
 company:()=>`<span class="frame-label">Simulated Virtual Company</span><h3>Meet Cirrus Sleep</h3><div class="mini-row"><div><div class="mini-stat">1,100+</div><p>Files in the supplied corpus</p></div><div class="mini-grid"><div class="mini-card">1 fiscal year</div><div class="mini-card">Financial records</div><div class="mini-card">Company decisions</div><div class="mini-card">Source-backed work</div></div></div>`,
 drive:()=>`<h3>Explore a complete fiscal year</h3><div class="mini-columns"><div><div class="tree-row selected">▾ Accounting</div><div class="tree-row">▸ Governance</div><div class="tree-row">▸ Operations</div></div><div class="mini-document">Public-source record<div class="mini-divider"></div><span class="frame-label">Filename · date · source</span><div class="paperline"></div><div class="paperline"></div><div class="paperline"></div></div></div>`,
 mandate:()=>`<span class="frame-label">Executive engagement · Abridged</span><h3>Prepare for the first external audit</h3><div class="mini-mandate"><p><b>Your role:</b> Controller</p><p><b>Your output:</b> Audit-readiness file</p><p><b>Your evidence:</b> The supplied company records</p></div><div class="mini-pills"><span class="pill">Level 3</span><span class="pill">~100 hours of professional work</span></div>`,
 tasks:()=>`<h3>Explore 10 independent tasks</h3><div class="task-mini-grid">${['Evidence','Cash','Revenue','Governance','Payroll','Inventory','Payables','Close','Contracts','Statements'].map((n,i)=>`<div class="${i<4?'seat':''}">${n}</div>`).join('')}</div><p>Own prompt · own reference answer · own rubric</p><div class="mini-pills"><span class="pill">4 journalist seats</span><span class="pill">Each task grades independently</span></div>`,
 seats:()=>`<h3>Take your seat</h3><div class="mini-grid">${[['A','Cash'],['B','Governance'],['C','Audit evidence'],['D','Revenue']].map(([a,b])=>`<div class="mini-card"><b>Seat ${a}</b> · ${b}<div class="sub">Prompt + 2–4 source files</div></div>`).join('')}</div><p>Work from the packet. Complete the deliverable yourself.</p>`,
 answer:()=>`<h3>Build your answer from the evidence</h3><div class="mini-columns"><div class="mini-document">Your packet<div class="paperline"></div><div class="paperline"></div><div class="paperline"></div></div><div class="mini-answer"><b>Your reference answer</b><div class="mini-divider"></div><p>Finding → source reference<br>Uncertainty → next action</p></div></div><p>Quiet working period · 22 minutes</p>`,
 rubric:()=>`<h3>Define what a correct answer requires</h3><table class="mini-table"><thead><tr><th>Criterion</th><th>Evidence</th><th>Weight</th></tr></thead><tbody><tr><td>A checkable requirement</td><td>Source reference</td><td>Points</td></tr><tr><td>A justified must-pass gate</td><td>Pass condition</td><td>Points</td></tr></tbody></table><div class="mini-pills"><span class="pill">10–20 criteria</span><span class="pill">100 points total</span><span class="pill">Check your own answer</span></div>`,
 inbox:()=>`<h3>Submit your work for review</h3><div class="mini-inbox"><span>Seat A · Deliverable + rubric</span><span>Received</span></div><div class="mini-inbox"><span>Seat B · Deliverable + rubric</span><span>In progress</span></div><div class="mini-inbox"><span>Seat C · Deliverable + rubric</span><span>In progress</span></div><p>Structural checks complete. Evidence review follows.</p>`,
 benchmark:()=>`<h3>Read the published benchmark result</h3><div class="metric-panel"><div><div class="mini-stat">20.3%</div><p>Highest all-core pass rate<br>in this snapshot</p></div><div class="chart-mini">${[['Opus 5',20.3],['GPT-5.6 Sol',16.8],['GPT-5.6 Terra',14.3]].map(([n,v])=>`<div class="bar-row"><span>${n}</span><div class="bar-track"><span style="width:${v}%"></span></div><span>${v}%</span></div>`).join('')}<p>Top 3 shown · 0–100% scale</p></div></div><p>30 tasks · 1,078 trials · 6 model/harness combinations</p>`,
 criterion:()=>`<h3>Apply your rubric to an attempt</h3><div class="mini-grid"><div class="mini-card">Recorded attempt<div class="sub">Model · harness · run date</div></div><div class="mini-card">Your criterion<div class="sub">Weight · must-pass status</div></div></div><div class="judgment">Source evidence → Reviewer judgment</div><div class="mini-pills"><span class="pill">Pass</span><span class="pill">Fail</span><span class="pill">Needs clarification</span></div>`,
 training:()=>`<h3>Use task feedback to improve models</h3><span class="frame-label">Training path</span><div class="mini-path"><span>Training tasks</span><i>→</i><span>Model update</span></div><span class="frame-label">Separate evaluation path</span><div class="mini-path"><span>Held-out tasks</span><i>→</i><span>Evidence review</span><i>→</i><span class="gate">Deployment gate</span></div>`,
 close:()=>`<span class="frame-label">Proposed extension</span><h3>Test what carries into year 2</h3><p>New company events. The investor’s perspective.</p><div class="mini-path"><span>Records</span><i>→</i><span>Task</span><i>→</i><span>Rubric</span><i>→</i><span>Evaluation</span></div><div class="judgment">What would you need to verify before relying on this work?</div>`
};
function frame(s){return `<div class="frame" role="img" aria-label="Storyboard screen concept: ${esc(s.screen)}"><div class="frame-head"><img src="assets/turing-logo.svg" alt="Turing"><span>CEO Bench</span></div><div class="frame-body">${frames[s.frame]()}</div><div class="frame-foot">${s.id===9?'Source: bench.turing.com · Sep 17, 2026 snapshot':s.id===10?'Concept frame · requires a recorded attempt':'Storyboard concept · internal planning'}</div></div>`}
function overview(){const visible=actFilter?scenes.filter(s=>s.act===actFilter):scenes;main.innerHTML=`<section class="hero"><div><div class="eyebrow">L1 Director’s Room · Internal production storyboard</div><h1>From company records<br>to an evidence-based judgment.</h1><p>A scene-by-scene plan for the CEO Bench press demo. Each scene pairs the intended screen with narration, participant action, evidence requirements, and the cue to continue.</p></div><div class="hero-summary"><div class="counts"><div><strong>5</strong><small>Presentation acts</small></div><div><strong>12</strong><small>Storyboard scenes</small></div><div><strong>82</strong><small>Minutes, plus questions</small></div></div><p>Journalists experience the work before examining how a model is evaluated. The hands-on workshop occupies 60 minutes.</p></div></section><nav class="acts" aria-label="Filter by act">${acts.map((a,i)=>`<button class="act ${actFilter===i+1?'active':''}" data-act="${i+1}" aria-pressed="${actFilter===i+1}"><span>Act ${i+1} · ${a.minutes} minutes</span><strong>${a.name}</strong></button>`).join('')}</nav><div class="board-top"><h2>${actFilter?acts[actFilter-1].name:'The complete sequence'}</h2>${actFilter?'<button class="outline-button" data-overview>Show all scenes</button>':'<small>Open a frame for the script and production cues.</small>'}</div><section class="board" aria-label="Storyboard scenes">${visible.map(s=>`<article class="scene-card"><button class="card-trigger" data-scene="${s.id}" aria-label="Open scene ${s.id}: ${esc(s.title)}"><div class="card-meta"><span class="scene-no">Scene ${String(s.id).padStart(2,'0')} · Act ${s.act}</span><span>${s.time} · ${s.minutes} min</span></div>${frame(s)}<div class="card-caption"><h3>${s.title}</h3><p>${s.intent}</p><span class="open">Read scene and cues ↗</span></div></button><div class="print-only"><b>Presenter:</b> ${s.narration}<br><b>Director:</b> ${s.director}<br><b>Journalist:</b> ${s.journalist}<br><b>Evidence:</b> ${s.evidence}<br><b>Transition:</b> ${s.transition}</div></article>`).join('')}</section>${footer()}`}
function footer(){return `<footer class="artifact-footer"><p>Built from the supplied demo outline and Turing’s brand references. Approved logo, Poppins, sentence case, grayscale, and selected blue accents. Rehearsal content and production requirements stay explicit.</p><p>September 23, 2026<br><a href="storyboard.md">Full script and source notes</a></p></footer>`}
function detail(id){const s=scenes.find(s=>s.id===id);if(!s){location.hash='';return}main.innerHTML=`<div class="detail-nav"><button class="outline-button" data-overview>← All scenes</button><div class="buttons"><button class="outline-button" data-scene="${id-1}" ${id===1?'disabled':''}>← Previous</button><button class="outline-button" data-scene="${id+1}" ${id===12?'disabled':''}>Next →</button></div></div><div class="detail-title"><div><span class="eyebrow">Act ${s.act} / ${acts[s.act-1].name} · Scene ${String(id).padStart(2,'0')}</span><h1>${s.title}</h1><p>${s.intent}</p></div><div class="time-chip">${s.time} · ${s.minutes} minutes</div></div><div class="detail-grid"><div class="detail-visual">${frame(s)}<p class="frame-note">Proposed screen composition. This is a storyboard frame, not a feature-completion claim.</p><nav class="act-progress" aria-label="Choose scene">${scenes.map(x=>`<a href="#scene-${x.id}" aria-label="Scene ${x.id}: ${esc(x.title)}" class="${id===x.id?'current':''}" ${id===x.id?'aria-current="step"':''}>${x.id}</a>`).join('')}</nav><div class="production"><span class="eyebrow">Build and asset status</span><p style="margin-top:8px">${s.status}</p><p style="margin-top:8px"><b>Asset needed:</b> ${s.asset}</p></div></div><div class="scene-notes"><section class="note-block narration"><h2>Presenter narration</h2><p>${s.narration}</p></section>${[['Director action',s.director],['Journalist action',s.journalist],['Evidence and disclosure',s.evidence],['Transition',s.transition],['Cue to continue',s.cue]].map(([h,p])=>`<section class="note-block"><h2>${h}</h2><p>${p}</p></section>`).join('')}</div></div>${footer()}`}
function route(){const match=location.hash.match(/^#scene-(\d+)$/);if(match)detail(+match[1]);else overview();window.scrollTo({top:0,behavior:'instant'})}
document.addEventListener('click',e=>{const scene=e.target.closest('[data-scene]');if(scene){location.hash='scene-'+scene.dataset.scene;return}const act=e.target.closest('[data-act]');if(act){actFilter=actFilter===+act.dataset.act?0:+act.dataset.act;overview();return}if(e.target.closest('[data-overview]')){actFilter=0;if(location.hash)location.hash='';else overview()}});
document.querySelector('#brand-button').onclick=()=>document.querySelector('#notes').showModal();document.querySelector('#close-notes').onclick=()=>document.querySelector('#notes').close();
document.addEventListener('keydown',e=>{if(document.querySelector('#notes').open)return;const m=location.hash.match(/^#scene-(\d+)$/);if(!m)return;const id=+m[1];if(e.key==='ArrowRight'&&id<12){e.preventDefault();location.hash='scene-'+(id+1)}if(e.key==='ArrowLeft'&&id>1){e.preventDefault();location.hash='scene-'+(id-1)}});
addEventListener('hashchange',route);route();
