'use strict';
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let actFilter=0;
const main=document.querySelector('main');
const frames={
 company:()=>`<span class="frame-label">Simulated Virtual Company</span><h3>Meet Cirrus Sleep</h3><div class="mini-row"><div><div class="mini-stat">1,100+</div><p>Files in the supplied corpus</p></div><div class="mini-grid"><div class="mini-card">Books and ledgers</div><div class="mini-card">Contracts</div><div class="mini-card">Payroll</div><div class="mini-card">Board decks</div><div class="mini-card">Internal Slack</div><div class="mini-card">1 fiscal year</div></div></div>`,
 drive:()=>`<h3>Explore a complete fiscal year</h3><div class="mini-columns"><div><div class="tree-row selected">▾ Accounting</div><div class="tree-row">▸ Governance</div><div class="tree-row">▸ Operations</div></div><div class="mini-document">Public-source record<div class="mini-divider"></div><span class="frame-label">Filename · date · source</span><div class="paperline"></div><div class="paperline"></div><div class="paperline"></div></div></div>`,
 mandate:()=>`<span class="frame-label">Executive engagement · Abridged</span><h3>Prepare for the first external audit</h3><div class="mini-mandate"><p><b>Your role:</b> Controller</p><p><b>Your output:</b> Audit-readiness file</p><p><b>Your evidence:</b> The supplied company records</p></div><div class="mini-pills"><span class="pill">Level 3</span><span class="pill">~100 hours of professional work</span></div>`,
 tasks:()=>`<h3>Explore 10 independent tasks</h3><div class="task-mini-grid">${['Cash & banking','Governance & equity','Audit evidence','Revenue & orders','Payroll','Inventory','Payables','Close','Contracts','Statements'].map((n,i)=>`<div class="${i<4?'seat':''}">${n}</div>`).join('')}</div><p>Own prompt · own reference answer · own rubric</p><div class="mini-pills"><span class="pill">4 pods, 1 task each</span><span class="pill">Each task grades independently</span></div>`,
 seats:()=>`<h3>Join your pod</h3><div class="mini-grid">${[['A','Cash & banking'],['B','Governance & equity'],['C','Audit evidence'],['D','Revenue & orders']].map(([a,b])=>`<div class="mini-card"><b>Pod ${a}</b> · ${b}<div class="sub">Prompt + 2–4 source files</div></div>`).join('')}</div><p>Work from the packet. Complete the deliverable yourselves.</p>`,
 answer:()=>`<h3>Build your answer from the evidence</h3><div class="mini-columns"><div class="mini-document">Your packet<div class="paperline"></div><div class="paperline"></div><div class="paperline"></div></div><div class="mini-answer"><b>Your reference answer</b><div class="mini-divider"></div><p>Finding → source reference<br>Uncertainty → next action</p></div></div><p>Quiet working period · 22 minutes</p>`,
 rubric:()=>`<h3>Define what a correct answer requires</h3><table class="mini-table"><thead><tr><th>Criterion</th><th>Evidence</th><th>Weight</th></tr></thead><tbody><tr><td>A checkable requirement</td><td>Source reference</td><td>Points</td></tr><tr><td>A justified must-pass gate</td><td>Pass condition</td><td>Points</td></tr></tbody></table><div class="mini-pills"><span class="pill">10–20 criteria</span><span class="pill">100 points total</span><span class="pill">Check your own answer</span></div>`,
 inbox:()=>`<h3>Submit your task for review</h3><div class="mini-inbox"><span>Pod A · Deliverable + rubric</span><span>Received</span></div><div class="mini-inbox"><span>Pod B · Deliverable + rubric</span><span>In progress</span></div><div class="mini-inbox"><span>Pod C · Deliverable + rubric</span><span>In progress</span></div><p>Structural checks complete. Evidence review follows.</p>`,
 baseline:()=>`<span class="frame-label">Pod A · Cash & banking · Baseline agent</span><h3>Run a baseline agent on your task</h3><div class="mini-columns"><div class="screen-rec"><span class="rec">● Recorded computer use</span><div class="rec-win"><div class="paperline"></div><div class="paperline"></div><div class="paperline"></div></div><span class="cursor">▲</span></div><div class="mini-answer"><span class="frame-label">Pre-run evaluation</span><div class="mini-stat">38<small>/100</small></div><p><span class="fail">Fails must-pass</span><br>Missed: planted conflict, source citation</p></div></div><div class="mini-pills"><span class="pill">▶ Run baseline</span><span class="pill">Open-weights model</span><span class="pill">Simulated</span></div>`,
 criterion:()=>`<h3>Grade the agent with your rubric</h3><div class="mini-columns"><div class="mini-card"><span class="frame-label">Your criterion 3 of 12 · must-pass</span><div class="sub">Flags the conflict between the bank statement and the ledger</div></div><div class="mini-document">Agent deliverable<div class="paperline"></div><div class="hl">“Balances reconcile with no exceptions.”</div><div class="paperline"></div></div></div><div class="mini-row"><div class="mini-pills"><span class="pill">Met</span><span class="pill on">Not met</span><span class="pill">Unclear</span></div><div class="judgment">Running total 34/100 · must-pass failed</div></div>`,
 training:()=>`<h3>Train the agent on expert data</h3><div class="mini-columns"><div class="mini-card"><span class="frame-label">Training dataset</span><div class="sub">Your golden answer<br>Your rubric as reward<br>Expert-built task variants</div></div><div class="mini-card"><span class="frame-label">Reward during training</span><svg viewBox="0 0 100 40" class="curve" aria-hidden="true"><polyline points="0,36 15,33 30,27 45,20 60,14 75,10 90,8 100,7"/></svg><div class="sub">Training steps →</div></div></div><div class="mini-pills"><span class="pill">▶ Start training run</span><span class="pill">Evaluation task held out</span><span class="pill">Simulated</span></div>`,
 checkpoint:()=>`<h3>Run the trained agent</h3><div class="mini-grid">${[['Baseline','Skips the conflicting records'],['Trained checkpoint','Checks both records, cites sources']].map(([a,b],i)=>`<div class="screen-rec ${i?'trained':''}"><span class="rec">● ${a}</span><div class="rec-win"><div class="paperline"></div><div class="paperline"></div></div><div class="sub">${b}</div></div>`).join('')}</div><div class="mini-pills"><span class="pill">Same prompt · same files</span><span class="pill">Pre-built checkpoint</span></div>`,
 reeval:()=>`<h3>Evaluate the trained agent again</h3><div class="metric-panel"><div><div class="mini-stat">+46<small> pts</small></div><p>38 → 84 on Pod A’s task<br>All must-pass gates cleared</p></div><div class="chart-mini">${[['Pod A',38,84],['Pod B',41,79],['Pod C',29,72],['Pod D',45,88]].map(([n,a,b])=>`<div class="bar-row"><span>${n}</span><div class="bar-track two"><span style="width:${b}%"></span><span style="width:${a}%"></span></div><span>${a}→${b}</span></div>`).join('')}</div></div><p>Before vs after · illustrative values</p>`,
 close:()=>`<h3>Congrats, you trained superintelligence today</h3><div class="mini-path"><span>Create a task</span><i>→</i><span>Evaluate</span><i>→</i><span>Train</span><i>→</i><span class="gate">Re-evaluate</span></div><div class="judgment">This is how Turing helps frontier labs specialize their agents.</div>`
};
function frame(s){return `<div class="frame" role="img" aria-label="Storyboard screen concept: ${esc(s.screen)}"><div class="frame-head"><img src="assets/turing-logo.svg" alt="Turing"><span>CEO Bench</span></div><div class="frame-body">${frames[s.frame]()}</div><div class="frame-foot">${[9,11,12].includes(s.id)?'Simulated run · recorded replay, no live model call':s.id===13?'Illustrative scores · replace with real run results':'Storyboard concept · internal planning'}</div></div>`}
function overview(){const visible=actFilter?scenes.filter(s=>s.act===actFilter):scenes;main.innerHTML=`<section class="hero"><div><div class="eyebrow">L1 Facilitator’s Room · Internal production storyboard</div><h1>Create a task. Evaluate an agent.<br>Train it. Evaluate again.</h1><p>A scene-by-scene plan for the CEO Bench press demo. Each pod creates a task, evaluates an agent on it, trains the agent with its expert data, and measures the improvement.</p></div><div class="hero-summary"><div class="counts"><div><strong>5</strong><small>Presentation acts</small></div><div><strong>${scenes.length}</strong><small>Storyboard scenes</small></div><div><strong>${scenes.reduce((n,s)=>n+s.minutes,0)}</strong><small>Minutes, plus questions</small></div></div><p>Journalists work in 4 pods, 1 task each. The hands-on workshop occupies 60 minutes; evaluation and training runs are simulated with recordings.</p></div></section><nav class="acts" aria-label="Filter by act">${acts.map((a,i)=>`<button class="act ${actFilter===i+1?'active':''}" data-act="${i+1}" aria-pressed="${actFilter===i+1}"><span>Act ${i+1} · ${a.minutes} minutes</span><strong>${a.name}</strong></button>`).join('')}</nav><div class="board-top"><h2>${actFilter?acts[actFilter-1].name:'The complete sequence'}</h2>${actFilter?'<button class="outline-button" data-overview>Show all scenes</button>':'<small>Open a frame for the script and production cues.</small>'}</div><section class="board" aria-label="Storyboard scenes">${visible.map(s=>`<article class="scene-card"><button class="card-trigger" data-scene="${s.id}" aria-label="Open scene ${s.id}: ${esc(s.title)}"><div class="card-meta"><span class="scene-no">Scene ${String(s.id).padStart(2,'0')} · Act ${s.act}</span><span>${s.time} · ${s.minutes} min</span></div>${frame(s)}<div class="card-caption"><h3>${s.title}</h3><p>${s.intent}</p><span class="open">Read scene and cues ↗</span></div></button><div class="print-only"><b>Presenter:</b> ${s.narration}<br><b>Facilitator:</b> ${s.facilitator}<br><b>Journalist:</b> ${s.journalist}<br><b>Evidence:</b> ${s.evidence}<br><b>Transition:</b> ${s.transition}</div></article>`).join('')}</section>${footer()}`}
function footer(){return `<footer class="artifact-footer"><p>Built from the supplied demo outline and Turing’s brand references. Approved logo, Poppins, sentence case, grayscale, and selected blue accents. Rehearsal content and production requirements stay explicit.</p><p>Updated September 30, 2026<br><a href="storyboard.md">Full script and source notes</a></p></footer>`}
function detail(id){const s=scenes.find(s=>s.id===id);if(!s){location.hash='';return}main.innerHTML=`<div class="detail-nav"><button class="outline-button" data-overview>← All scenes</button><div class="buttons"><button class="outline-button" data-scene="${id-1}" ${id===1?'disabled':''}>← Previous</button><button class="outline-button" data-scene="${id+1}" ${id===scenes.length?'disabled':''}>Next →</button></div></div><div class="detail-title"><div><span class="eyebrow">Act ${s.act} / ${acts[s.act-1].name} · Scene ${String(id).padStart(2,'0')}</span><h1>${s.title}</h1><p>${s.intent}</p></div><div class="time-chip">${s.time} · ${s.minutes} minutes</div></div><div class="detail-grid"><div class="detail-visual">${frame(s)}<p class="frame-note">Proposed screen composition. This is a storyboard frame, not a feature-completion claim.</p><nav class="act-progress" aria-label="Choose scene">${scenes.map(x=>`<a href="#scene-${x.id}" aria-label="Scene ${x.id}: ${esc(x.title)}" class="${id===x.id?'current':''}" ${id===x.id?'aria-current="step"':''}>${x.id}</a>`).join('')}</nav><div class="production"><span class="eyebrow">Build and asset status</span><p style="margin-top:8px">${s.status}</p><p style="margin-top:8px"><b>Asset needed:</b> ${s.asset}</p></div></div><div class="scene-notes"><section class="note-block narration"><h2>Presenter narration</h2><p>${s.narration}</p></section>${[['Facilitator action',s.facilitator],['Journalist action',s.journalist],['Evidence and disclosure',s.evidence],['Transition',s.transition],['Cue to continue',s.cue]].map(([h,p])=>`<section class="note-block"><h2>${h}</h2><p>${p}</p></section>`).join('')}</div></div>${footer()}`}
function route(){const match=location.hash.match(/^#scene-(\d+)$/);if(match)detail(+match[1]);else overview();window.scrollTo({top:0,behavior:'instant'})}
document.addEventListener('click',e=>{const scene=e.target.closest('[data-scene]');if(scene){location.hash='scene-'+scene.dataset.scene;return}const act=e.target.closest('[data-act]');if(act){actFilter=actFilter===+act.dataset.act?0:+act.dataset.act;overview();return}if(e.target.closest('[data-overview]')){actFilter=0;if(location.hash)location.hash='';else overview()}});
document.querySelector('#brand-button').onclick=()=>document.querySelector('#notes').showModal();document.querySelector('#close-notes').onclick=()=>document.querySelector('#notes').close();
document.addEventListener('keydown',e=>{if(document.querySelector('#notes').open)return;const m=location.hash.match(/^#scene-(\d+)$/);if(!m)return;const id=+m[1];if(e.key==='ArrowRight'&&id<scenes.length){e.preventDefault();location.hash='scene-'+(id+1)}if(e.key==='ArrowLeft'&&id>1){e.preventDefault();location.hash='scene-'+(id-1)}});
addEventListener('hashchange',route);route();
